import {
  FamilyCardData,
  SpendChartData,
  SpendControlData,
  FamilyMember,
  SubAccount,
  Transaction,
  Permission,
} from "./types";
import { CATEGORY_COLORS } from "./constants";

export const mockFamilyMembers: FamilyMember[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    email: "sarah@johnson.com",
    role: "parent",
    age: 42,
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "2",
    name: "Michael Johnson",
    email: "michael@johnson.com",
    role: "parent",
    age: 44,
    avatar: "https://i.pravatar.cc/150?img=12",
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "3",
    name: "Emma Johnson",
    email: "emma@johnson.com",
    role: "child",
    age: 14,
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "4",
    name: "Lucas Johnson",
    email: "lucas@johnson.com",
    role: "child",
    age: 12,
    avatar: "https://i.pravatar.cc/150?img=8",
    createdAt: new Date("2024-01-15"),
  },
];

export const mockSubAccounts: SubAccount[] = [
  {
    id: "sub-1",
    memberId: "1",
    balance: 750.5,
    spendLimit: 1000,
    spendPeriod: "monthly",
    permissions: "full",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-10-15"),
  },
  {
    id: "sub-2",
    memberId: "2",
    balance: 450.25,
    spendLimit: 1000,
    spendPeriod: "monthly",
    permissions: "full",
    isActive: true,
    createdAt: new Date("2024-01-01"),
    updatedAt: new Date("2024-10-15"),
  },
  {
    id: "sub-3",
    memberId: "3",
    balance: 180.0,
    spendLimit: 200,
    spendPeriod: "weekly",
    permissions: "limited",
    isActive: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-14"),
  },
  {
    id: "sub-4",
    memberId: "4",
    balance: 95.5,
    spendLimit: 150,
    spendPeriod: "weekly",
    permissions: "view-only",
    isActive: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-10-10"),
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn-1",
    subAccountId: "sub-3",
    memberId: "3",
    amount: 45.99,
    type: "debit",
    category: "shopping",
    description: "Clothing purchase",
    merchant: "Fashion Store",
    status: "completed",
    timestamp: new Date("2024-10-15T10:30:00"),
  },
  {
    id: "txn-2",
    subAccountId: "sub-1",
    memberId: "1",
    amount: 125.5,
    type: "debit",
    category: "food",
    description: "Grocery shopping",
    merchant: "Whole Foods",
    status: "completed",
    timestamp: new Date("2024-10-15T14:20:00"),
  },
  {
    id: "txn-3",
    subAccountId: "sub-3",
    memberId: "3",
    amount: 50.0,
    type: "credit",
    category: "other",
    description: "Weekly allowance",
    status: "completed",
    timestamp: new Date("2024-10-14T09:00:00"),
  },
  {
    id: "txn-4",
    subAccountId: "sub-2",
    memberId: "2",
    amount: 85.0,
    type: "debit",
    category: "transport",
    description: "Gas station",
    merchant: "Shell",
    status: "completed",
    timestamp: new Date("2024-10-14T16:45:00"),
  },
  {
    id: "txn-5",
    subAccountId: "sub-4",
    memberId: "4",
    amount: 60.0,
    type: "debit",
    category: "entertainment",
    description: "Video game purchase",
    merchant: "GameStop",
    status: "pending",
    timestamp: new Date("2024-10-13T11:15:00"),
    metadata: {
      requiresApproval: true,
    },
  },
  {
    id: "txn-6",
    subAccountId: "sub-3",
    memberId: "3",
    amount: 15.99,
    type: "debit",
    category: "food",
    description: "Fast food",
    merchant: "McDonald's",
    status: "completed",
    timestamp: new Date("2024-10-13T12:30:00"),
  },
  {
    id: "txn-7",
    subAccountId: "sub-1",
    memberId: "1",
    amount: 200.0,
    type: "debit",
    category: "education",
    description: "School supplies",
    merchant: "Office Depot",
    status: "completed",
    timestamp: new Date("2024-10-12T10:00:00"),
  },
  {
    id: "txn-8",
    subAccountId: "sub-2",
    memberId: "2",
    amount: 75.0,
    type: "debit",
    category: "entertainment",
    description: "Movie tickets",
    merchant: "AMC Theaters",
    status: "completed",
    timestamp: new Date("2024-10-11T19:30:00"),
  },
];

export const mockPermissions: Permission[] = [
  {
    subAccountId: "sub-1",
    canTransfer: true,
    canViewFamily: true,
    canRequestFunds: true,
    requiresApproval: false,
  },
  {
    subAccountId: "sub-2",
    canTransfer: true,
    canViewFamily: true,
    canRequestFunds: true,
    requiresApproval: false,
  },
  {
    subAccountId: "sub-3",
    canTransfer: false,
    canViewFamily: true,
    canRequestFunds: true,
    requiresApproval: true,
    approvalThreshold: 50,
  },
  {
    subAccountId: "sub-4",
    canTransfer: false,
    canViewFamily: false,
    canRequestFunds: true,
    requiresApproval: true,
    approvalThreshold: 25,
  },
];

export const mockFamilyCardData: FamilyCardData[] = [
  {
    id: "1",
    name: "Sarah Johnson",
    role: "parent",
    balance: 750.5,
    spendLimit: 1000,
    isActive: true,
  },
  {
    id: "2",
    name: "Michael Johnson",
    role: "parent",
    avatar: "https://i.pravatar.cc/150?img=12",
    balance: 450.25,
    spendLimit: 1000,
    isActive: true,
  },
  {
    id: "3",
    name: "Emma Johnson",
    role: "child",
    balance: 180.0,
    spendLimit: 200,
    isActive: true,
  },
  {
    id: "4",
    name: "Lucas Johnson",
    role: "child",
    avatar: "https://i.pravatar.cc/150?img=8",
    balance: 95.5,
    spendLimit: 150,
    isActive: false,
  },
];

export const mockSpendChartData: SpendChartData = {
  categories: [
    {
      name: "food",
      amount: 450.75,
      color: CATEGORY_COLORS.food,
    },
    {
      name: "transport",
      amount: 125.5,
      color: CATEGORY_COLORS.transport,
    },
    {
      name: "entertainment",
      amount: 89.99,
      color: CATEGORY_COLORS.entertainment,
    },
    {
      name: "education",
      amount: 200.0,
      color: CATEGORY_COLORS.education,
    },
    {
      name: "shopping",
      amount: 156.23,
      color: CATEGORY_COLORS.shopping,
    },
  ],
  totalSpent: 1022.47,
  totalBudget: 1500.0,
  period: "monthly",
};

export const mockSpendControlData: SpendControlData = {
  memberId: "3",
  memberName: "Emma Johnson",
  currentSpending: 140.5,
  dailyLimit: 20.0,
  weeklyLimit: 75.0,
  monthlyLimit: 200.0,
  period: "weekly",
};

export const mockEmptySpendChartData: SpendChartData = {
  categories: [],
  totalSpent: 0,
  totalBudget: 1500.0,
  period: "monthly",
};
